### ISSUE TITLE
add option to get stats from pseudo (whithout plex.tv connection)

### ISSUE THREAD

**Issue by JamesDAdams** [aunefyren/wrapperr#22]
Hi,

i would like an option to get stats from a user pseudo, for don't use the plex.tv server.

Thanks

**Comment by aunefyren** [comment]
> user pseudo

 Hi, I would love to implement some changes for you, but I don't really understand the request. Could you give a detailed explaination of what a user pseudo is and how you want stats to be gathered from it?

**Comment by JamesDAdams** [comment]
Make sure that instead of connecting to plex.tv, we type the nickname of a user who is connected to the plex server.

just with the username we can retrieve the stats from tautulli.

This feature would be really good for people like me who want to be able to use their services without internet.

**Comment by sucr4m** [comment]
heh, funny enough thats how it worked before. you might wanna get 2.0 just to try that.

**Comment by BrianLindner** [comment]
I too would add to the "request ability to run offline for specific users" option...  I did try to v2.0.0 and while it does work, it obviously wont have the latest features/enhancements/updates :-( 

Maybe a config for which "mode" to run the User selection in:  Plex Auth, or email/username search...   

my reason to request that ability: 
* generating for Managed users (they dont have separate Plex Auth to utilize) -ex: local family users
* Generating pre-reports for people.. as may not want to run Plex-Wrapped with outside user access. Could pre-run, and print to PDF for saving, etc (on my own)

**Comment by aunefyren** [comment]
> Generating pre-reports for people.. as may not want to run Plex-Wrapped with outside user access. Could pre-run, and print to PDF for saving, etc (on my own)

I am considering some form of premade generation/saving/email-implementation either way, but I absolutely understand adding an option to disable Plex Auth is a good idea.

**Comment by aunefyren** [comment]
> also a little less funny the plex auth only tells me "Plex Auth did not respond." so having a switch to let the admin chose what to use would be nice.

That's not good! Do you think it's your setup/Plex Servers being weird, or does my code need some tweaking?

**Comment by sucr4m** [comment]
- one month later

idk what it was but since then i moved my plex to unraid and your wrapper docker container is working fine. thanks for asking.

i do wonder though.. im just reading myself into docker and unraid for now but it seems with your container you are using your own php file right? the php,ini-production one? why arent you upping the numbers for execution time and memory limit out of the box? it seems like such a small tweak..

also while im not sure if this is the right place but reading through the changelogs i do seem to be missing half the functionality?
where do i find the links? how do i create them?

and last but not least despite selecting server wide stats its not showing any.

**Comment by aunefyren** [comment]
> why arent you upping the numbers for execution time and memory limit out of the box? it seems like such a small tweak..

That is a fair point, and definitely something I might consider. The issue is what the settings should be tweaked to as this is dependent on what period is customized, the data available in Tautulli and the capacity of the machine. It is unique for every user.

> missing half the functionality?
> where do i find the links? how do i create them?

Checking 'Allow shareable link creation' in 'Wrapperr settings' means users can click Share page on the bottom of their stat page. Sorry if this was not clear. Any more functionality that seems missing?

> selecting server wide stats its not showing any. i have tried my admin acc which i use to watch everything and a guest acc that didnt have any watches. both dont show them though.

Someone else reported this too, so it seems to be a bug that showed up recently. At least no one has mentioned it before to my knowledge.

**Comment by sucr4m** [comment]
i had it [turned on](https://i.imgur.com/Oyx55Ih.png) from the start. But its [not showing at the bottom](https://i.imgur.com/uNZarYw.png). Maybe there is some small error cutting off the page since like mentioned before, server wide stuff isnt there either. i cant speak for the versions inbetween since i directly jumped from 2.0 on windows to 2.2.1 on docker.

**Comment by aunefyren** [comment]
> i had it [turned on](https://i.imgur.com/Oyx55Ih.png) from the start. But its [not showing at the bottom](https://i.imgur.com/uNZarYw.png). Maybe there is some small error cutting off the page since like mentioned before, server wide stuff isnt there either. i cant speak for the versions inbetween since i directly jumped from 2.0 on windows to 2.2.1 on docker.

Yeah, I see both server-wide and the outro section (which contains the 'share' button) is missing. Any JS errors in the browsers console?

**Comment by sucr4m** [comment]
something like this?

`
element.style {
}
.color-orangeyellow {
    background-color: var(--orangeyellow);
    transition-duration: 1s;
}
body {
    padding: 0;
    margin: 0;
    height: 100%;
    width: 100%;
    font-family: 'Roboto', serif;
    font-weight: normal;
    background-color: var(--mango);
    box-sizing: border-box;
}
user agent stylesheet
body {
    display: block;
    margin: 8px;
}
:root {
    --red: #F94144;
    --orangered: #F3722C;
    --orangeyellow: #F8961E;
    --mango: #F9844A;
    --yellow: #F9C74F;
    --pistach: #90BE6D;
    --green: #43AA8B;
    --cadetblue: #4D908E;
    --queenblue: #577590;
    --blue: #277DA1;
    --white: #f1f1f1;
    --black: #181818;
    --charcoal: #414141;
}
﻿
functions.js:182 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at number_with_spaces (functions.js:182:19)
    at seconds_to_seconds (functions.js:175:26)
    at seconds_to_time (get_stats.js:971:20)
    at load_users (get_stats.js:788:36)
    at load_page (get_stats.js:103:9)
    at XMLHttpRequest.xhttp.onreadystatechange (get_stats.js:49:17)`

**Comment by aunefyren** [comment]
> something like this?
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
>     at number_with_spaces (functions.js:182:19)
>     at seconds_to_seconds (functions.js:175:26)
>     at seconds_to_time (get_stats.js:971:20)
>     at load_users (get_stats.js:788:36)
>     at load_page (get_stats.js:103:9)
>     at XMLHttpRequest.xhttp.onreadystatechange (get_stats.js:49:17)
> ```

Yes, thank you! I know have a clue about what might be causing this :)

**Comment by aunefyren** [comment]
> yo, just wanted to report back: you managed to fix it. nice work. you still have that thing though where it [doesnt combine partial plays](https://i.imgur.com/9kXwMW2.png) while [tautulli shows it correct](https://i.imgur.com/XPPlHqK.png). i mentioned it once on reddit i think.

Thank you! I investigated the issue and it seems to be based on how Tautulli does grouping. It has been added to the FAQ in the README.

**Comment by aunefyren** [comment]
Added to v2.2.4
